
server:
  port: 8888

spring:
  application:
    name: config-server
     # 必须是jdbc 因为是默认的
  profiles:
    active:
    - jdbc    
  cloud:
    config:
      server:
        # jdbc配置数据源  
        jdbc:
          sql: SELECT properties_KEY, properties_VALUE from SysProperties where APPLICATION=? and PROFILE=? and LABEL=?
  security:
    user:
      name: sa
      password: pwd123456
  datasource:
    url: jdbc:sqlserver://192.168.1.3;DatabaseName=wangxiao2_sys
    username: sa
    password: sad!##DSEDw323343
    type: com.alibaba.druid.pool.DruidDataSource
 
management:
  endpoints:
    web:
      exposure:
        include:
        - health,info,refresh